version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: s-io-postgres
    environment:
      POSTGRES_DB: yggdrasil
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: JGRsolomon0924$
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  qdrant:
    image: qdrant/qdrant:latest
    container_name: s-io-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      QDRANT__SERVICE__HTTP_PORT: 6333
      QDRANT__SERVICE__GRPC_PORT: 6334
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:6333/collections || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  s-io:
    build: .
    container_name: s-io-app
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      qdrant:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:JGRsolomon0924$@postgres:5432/yggdrasil
      QDRANT_URL: http://qdrant:6333
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    command: ["python", "-m", "solomon.main"]

volumes:
  postgres_data:
  qdrant_data:
