
-- S.IO Forest Structure Data Migration  
-- Populates initial tree/branch/limb structure
-- Date: 2025-06-22

-- Insert Trees
INSERT INTO trees (name, description) VALUES ('astrology', 'Knowledge domain for astrology');
INSERT INTO trees (name, description) VALUES ('history', 'Knowledge domain for history');
INSERT INTO trees (name, description) VALUES ('philosophy', 'Knowledge domain for philosophy');
INSERT INTO trees (name, description) VALUES ('religion', 'Knowledge domain for religion');
INSERT INTO trees (name, description) VALUES ('science', 'Knowledge domain for science');

-- Insert Branches
INSERT INTO branches (tree_id, name, description) SELECT id, 'chinese_astrology', 'Branch for chinese astrology' FROM trees WHERE name = 'astrology';
INSERT INTO branches (tree_id, name, description) SELECT id, 'esoteric_astrology', 'Branch for esoteric astrology' FROM trees WHERE name = 'astrology';
INSERT INTO branches (tree_id, name, description) SELECT id, 'mundane_astrology', 'Branch for mundane astrology' FROM trees WHERE name = 'astrology';
INSERT INTO branches (tree_id, name, description) SELECT id, 'natal_astrology', 'Branch for natal astrology' FROM trees WHERE name = 'astrology';
INSERT INTO branches (tree_id, name, description) SELECT id, 'vedic_astrology', 'Branch for vedic astrology' FROM trees WHERE name = 'astrology';
INSERT INTO branches (tree_id, name, description) SELECT id, 'western_astrology', 'Branch for western astrology' FROM trees WHERE name = 'astrology';
INSERT INTO branches (tree_id, name, description) SELECT id, 'ancient_history', 'Branch for ancient history' FROM trees WHERE name = 'history';
INSERT INTO branches (tree_id, name, description) SELECT id, 'medieval_history', 'Branch for medieval history' FROM trees WHERE name = 'history';
INSERT INTO branches (tree_id, name, description) SELECT id, 'modern_history', 'Branch for modern history' FROM trees WHERE name = 'history';
INSERT INTO branches (tree_id, name, description) SELECT id, 'aesthetics', 'Branch for aesthetics' FROM trees WHERE name = 'philosophy';
INSERT INTO branches (tree_id, name, description) SELECT id, 'ancient_philosophy', 'Branch for ancient philosophy' FROM trees WHERE name = 'philosophy';
INSERT INTO branches (tree_id, name, description) SELECT id, 'contemporary_philosophy', 'Branch for contemporary philosophy' FROM trees WHERE name = 'philosophy';
INSERT INTO branches (tree_id, name, description) SELECT id, 'eastern philosophy', 'Branch for eastern philosophy' FROM trees WHERE name = 'philosophy';
INSERT INTO branches (tree_id, name, description) SELECT id, 'epistemology', 'Branch for epistemology' FROM trees WHERE name = 'philosophy';
INSERT INTO branches (tree_id, name, description) SELECT id, 'ethics', 'Branch for ethics' FROM trees WHERE name = 'philosophy';
INSERT INTO branches (tree_id, name, description) SELECT id, 'existentialism', 'Branch for existentialism' FROM trees WHERE name = 'philosophy';
INSERT INTO branches (tree_id, name, description) SELECT id, 'logic', 'Branch for logic' FROM trees WHERE name = 'philosophy';
INSERT INTO branches (tree_id, name, description) SELECT id, 'medieval_philosophy', 'Branch for medieval philosophy' FROM trees WHERE name = 'philosophy';
INSERT INTO branches (tree_id, name, description) SELECT id, 'metaphysics', 'Branch for metaphysics' FROM trees WHERE name = 'philosophy';
INSERT INTO branches (tree_id, name, description) SELECT id, 'modern_philosophy', 'Branch for modern philosophy' FROM trees WHERE name = 'philosophy';
INSERT INTO branches (tree_id, name, description) SELECT id, 'phenomenology', 'Branch for phenomenology' FROM trees WHERE name = 'philosophy';
INSERT INTO branches (tree_id, name, description) SELECT id, 'philosophers', 'Branch for philosophers' FROM trees WHERE name = 'philosophy';
INSERT INTO branches (tree_id, name, description) SELECT id, 'philosophy of religion', 'Branch for philosophy of religion' FROM trees WHERE name = 'philosophy';
INSERT INTO branches (tree_id, name, description) SELECT id, 'political philosophy', 'Branch for political philosophy' FROM trees WHERE name = 'philosophy';
INSERT INTO branches (tree_id, name, description) SELECT id, 'buddhism', 'Branch for buddhism' FROM trees WHERE name = 'religion';
INSERT INTO branches (tree_id, name, description) SELECT id, 'christianity', 'Branch for christianity' FROM trees WHERE name = 'religion';
INSERT INTO branches (tree_id, name, description) SELECT id, 'hinduism', 'Branch for hinduism' FROM trees WHERE name = 'religion';
INSERT INTO branches (tree_id, name, description) SELECT id, 'islam', 'Branch for islam' FROM trees WHERE name = 'religion';
INSERT INTO branches (tree_id, name, description) SELECT id, 'judaism', 'Branch for judaism' FROM trees WHERE name = 'religion';
INSERT INTO branches (tree_id, name, description) SELECT id, 'astronomy', 'Branch for astronomy' FROM trees WHERE name = 'science';
INSERT INTO branches (tree_id, name, description) SELECT id, 'biology', 'Branch for biology' FROM trees WHERE name = 'science';
INSERT INTO branches (tree_id, name, description) SELECT id, 'chemistry', 'Branch for chemistry' FROM trees WHERE name = 'science';
INSERT INTO branches (tree_id, name, description) SELECT id, 'computer_science', 'Branch for computer science' FROM trees WHERE name = 'science';
INSERT INTO branches (tree_id, name, description) SELECT id, 'mathematics', 'Branch for mathematics' FROM trees WHERE name = 'science';
INSERT INTO branches (tree_id, name, description) SELECT id, 'physics', 'Branch for physics' FROM trees WHERE name = 'science';

-- Insert Limbs
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'classical_systems', 'Category for classical systems' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'astrology' AND b.name = 'chinese_astrology';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'feng_shui_astrology', 'Category for feng shui astrology' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'astrology' AND b.name = 'chinese_astrology';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'traditional_texts', 'Category for traditional texts' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'astrology' AND b.name = 'chinese_astrology';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'hermetic_astrology', 'Category for hermetic astrology' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'astrology' AND b.name = 'esoteric_astrology';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'karmic_astrology', 'Category for karmic astrology' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'astrology' AND b.name = 'esoteric_astrology';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'soul_astrology', 'Category for soul astrology' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'astrology' AND b.name = 'esoteric_astrology';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'economic_astrology', 'Category for economic astrology' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'astrology' AND b.name = 'mundane_astrology';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'natural_disasters', 'Category for natural disasters' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'astrology' AND b.name = 'mundane_astrology';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'political_astrology', 'Category for political astrology' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'astrology' AND b.name = 'mundane_astrology';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'chart_interpretation', 'Category for chart interpretation' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'astrology' AND b.name = 'natal_astrology';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'house_systems', 'Category for house systems' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'astrology' AND b.name = 'natal_astrology';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'timing_techniques', 'Category for timing techniques' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'astrology' AND b.name = 'natal_astrology';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'classical_texts', 'Category for classical texts' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'astrology' AND b.name = 'vedic_astrology';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'computational_methods', 'Category for computational methods' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'astrology' AND b.name = 'vedic_astrology';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'predictive_techniques', 'Category for predictive techniques' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'astrology' AND b.name = 'vedic_astrology';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'classical_astrology', 'Category for classical astrology' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'astrology' AND b.name = 'western_astrology';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'horary_astrology', 'Category for horary astrology' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'astrology' AND b.name = 'western_astrology';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'modern_astrology', 'Category for modern astrology' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'astrology' AND b.name = 'western_astrology';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'classical_antiquity', 'Category for classical antiquity' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'history' AND b.name = 'ancient_history';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'egypt', 'Category for egypt' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'history' AND b.name = 'ancient_history';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'mesopotamia', 'Category for mesopotamia' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'history' AND b.name = 'ancient_history';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'early_medieval', 'Category for early medieval' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'history' AND b.name = 'medieval_history';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'high_medieval', 'Category for high medieval' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'history' AND b.name = 'medieval_history';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'late_medieval', 'Category for late medieval' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'history' AND b.name = 'medieval_history';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'enlightenment', 'Category for enlightenment' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'history' AND b.name = 'modern_history';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'industrial_age', 'Category for industrial age' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'history' AND b.name = 'modern_history';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'renaissance', 'Category for renaissance' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'history' AND b.name = 'modern_history';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'greek_philosophy', 'Category for greek philosophy' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'philosophy' AND b.name = 'ancient_philosophy';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'hellenistic_philosophy', 'Category for hellenistic philosophy' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'philosophy' AND b.name = 'ancient_philosophy';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'roman_philosophy', 'Category for roman philosophy' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'philosophy' AND b.name = 'ancient_philosophy';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'analytic_philosophy', 'Category for analytic philosophy' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'philosophy' AND b.name = 'contemporary_philosophy';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'continental_philosophy', 'Category for continental philosophy' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'philosophy' AND b.name = 'contemporary_philosophy';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'existentialism', 'Category for existentialism' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'philosophy' AND b.name = 'contemporary_philosophy';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'limbs.json', 'Category for limbs.json' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'philosophy' AND b.name = 'eastern philosophy';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'islamic_philosophy', 'Category for islamic philosophy' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'philosophy' AND b.name = 'medieval_philosophy';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'jewish_philosophy', 'Category for jewish philosophy' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'philosophy' AND b.name = 'medieval_philosophy';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'scholasticism', 'Category for scholasticism' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'philosophy' AND b.name = 'medieval_philosophy';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'ontological', 'Category for ontological' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'philosophy' AND b.name = 'metaphysics';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'empiricism', 'Category for empiricism' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'philosophy' AND b.name = 'modern_philosophy';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'german_idealism', 'Category for german idealism' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'philosophy' AND b.name = 'modern_philosophy';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'rationalism', 'Category for rationalism' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'philosophy' AND b.name = 'modern_philosophy';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'limbs.json', 'Category for limbs.json' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'philosophy' AND b.name = 'philosophers';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'canonical_texts', 'Category for canonical texts' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'religion' AND b.name = 'buddhism';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'commentaries', 'Category for commentaries' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'religion' AND b.name = 'buddhism';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'meditation_texts', 'Category for meditation texts' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'religion' AND b.name = 'buddhism';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'biblical_texts', 'Category for biblical texts' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'religion' AND b.name = 'christianity';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'catholic', 'Category for catholic' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'religion' AND b.name = 'christianity';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'denominational_texts', 'Category for denominational texts' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'religion' AND b.name = 'christianity';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'orthodox', 'Category for orthodox' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'religion' AND b.name = 'christianity';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'patristic_literature', 'Category for patristic literature' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'religion' AND b.name = 'christianity';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'protestant', 'Category for protestant' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'religion' AND b.name = 'christianity';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'epic_literature', 'Category for epic literature' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'religion' AND b.name = 'hinduism';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'philosophical_texts', 'Category for philosophical texts' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'religion' AND b.name = 'hinduism';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'vedic_texts', 'Category for vedic texts' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'religion' AND b.name = 'hinduism';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'islamic_philosophy', 'Category for islamic philosophy' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'religion' AND b.name = 'islam';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'islamic_texts', 'Category for islamic texts' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'religion' AND b.name = 'islam';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'jurisprudence', 'Category for jurisprudence' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'religion' AND b.name = 'islam';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'hebrew_scriptures', 'Category for hebrew scriptures' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'religion' AND b.name = 'judaism';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'mystical_texts', 'Category for mystical texts' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'religion' AND b.name = 'judaism';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'rabbinical_literature', 'Category for rabbinical literature' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'religion' AND b.name = 'judaism';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'artificial_intelligence', 'Category for artificial intelligence' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'science' AND b.name = 'computer_science';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'limbs', 'Category for limbs' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'science' AND b.name = 'computer_science';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'programming', 'Category for programming' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'science' AND b.name = 'computer_science';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'theoretical_cs', 'Category for theoretical cs' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'science' AND b.name = 'computer_science';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'applied_mathematics', 'Category for applied mathematics' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'science' AND b.name = 'mathematics';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'modern_mathematics', 'Category for modern mathematics' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'science' AND b.name = 'mathematics';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'pure_mathematics', 'Category for pure mathematics' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'science' AND b.name = 'mathematics';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'classical_physics', 'Category for classical physics' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'science' AND b.name = 'physics';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'quantum_mechanics', 'Category for quantum mechanics' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'science' AND b.name = 'physics';
INSERT INTO limbs (branch_id, name, description) SELECT b.id, 'relativity', 'Category for relativity' FROM branches b JOIN trees t ON b.tree_id = t.id WHERE t.name = 'science' AND b.name = 'physics';